"use client";
import { useState } from "react";

const whatsapp="https://wa.me/51941075992?text=Hola%20NUBA%2C%20quiero%20contarte%20sobre%20mi%20negocio";
const instagram="https://instagram.com/nuba.agenciacreativa";
const email="mailto:nubaagenciacreativa@gmail.com";
const services=[
 ["01","Gestión de Redes Sociales","Planificamos, creamos y gestionamos el contenido para mantener una presencia constante, clara y profesional."],
 ["02","Creación de Contenido","Fotografía, video, reels y piezas que muestran lo mejor de tu producto, servicio y forma de trabajar."],
 ["03","Campañas Publicitarias","Conceptos y contenido para promociones, lanzamientos, fechas especiales y objetivos comerciales."],
 ["04","Identidad Visual","Creamos una identidad reconocible y coherente para que tu negocio se vea tan profesional como es."],
 ["05","Diseño para Negocios","Catálogos, flyers, presentaciones y materiales digitales listos para comunicar mejor."],
 ["06","Contenido con IA","Usamos nuevas herramientas creativas para producir ideas ágiles sin perder la esencia de tu marca."]
];
const process=[
 ["01","Descubre","Conocemos tu negocio y lo que quieres lograr."],["02","Planifica","Definimos una ruta clara para tu contenido."],["03","Crea","Producimos las piezas con dirección visual."],["04","Conecta","Llevamos tu mensaje a las personas correctas."],["05","Impulsa","Medimos, aprendemos y seguimos creciendo."]
];

export default function Home(){
 const [open,setOpen]=useState(false); const close=()=>setOpen(false);
 return <>
  <a className="skip-link" href="#contenido">Saltar al contenido</a>
  <header className="site-header"><div className="container nav"><a className="brand" href="#inicio" onClick={close}>NUBA<span>.</span></a><nav className="nav-links"><a href="#servicios">Servicios</a><a href="#trabajos">Trabajos</a><a href="#metodo">Método</a><a href="#nuba">Nosotras</a><a className="btn btn-primary" href={whatsapp} target="_blank" rel="noreferrer">Hablemos</a></nav><button className="menu-btn" onClick={()=>setOpen(!open)} aria-expanded={open}>Menú</button></div><nav className={open?"mobile-menu open":"mobile-menu"}><a href="#servicios" onClick={close}>Servicios</a><a href="#trabajos" onClick={close}>Trabajos</a><a href="#metodo" onClick={close}>Método</a><a href="#nuba" onClick={close}>Nosotras</a><a href={whatsapp}>Hablemos →</a></nav></header>
  <main id="contenido">
   <section className="hero" id="inicio"><div className="container hero-grid"><div><p className="eyebrow">NUBA / Agencia Creativa</p><h1>Creamos contenido para hacer crecer tu negocio<span>.</span></h1><div className="hero-mark"/></div><div className="hero-copy"><p className="hero-sub">Redes sociales · Fotografía · Video · Diseño</p><p className="lead">Contenido claro, profesional y pensado para mostrar lo mejor de tu negocio.</p><div className="hero-actions"><a className="btn btn-primary" href={whatsapp} target="_blank" rel="noreferrer">Cuéntanos sobre tu negocio →</a><a className="btn" href="#trabajos">Ver trabajos</a></div></div><div className="visual-strip"><div className="visual visual-main"><div className="camera-frame"><i>REC</i><strong>Tu negocio<br/>merece ser visto.</strong><span>PRODUCCIÓN DE CONTENIDO</span></div></div><div className="visual visual-light"><div className="nuba-card"><small>CREATIVIDAD<br/>CON DIRECCIÓN</small><b>N.</b><span>CAMANÁ / AREQUIPA</span></div></div></div></div></section>
   <section className="section" id="servicios"><div className="container"><p className="eyebrow">01 / Servicios</p><h2 className="section-title">¿Cómo podemos ayudarte?</h2><div className="services-grid">{services.map(([n,t,d])=><article className="service-row" key={n}><span className="service-no">{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></div></section>
   <section className="section work-section" id="trabajos"><div className="container"><p className="eyebrow">02 / Trabajos</p><h2 className="section-title">Mira lo que podemos crear.</h2><p className="lead">Estrategia y creatividad aplicadas a marcas que quieren comunicar mejor.</p><div className="portfolio-grid"><article className="project featured"><div className="project-media media-one"><span className="mini-label">IDENTIDAD / CONTENIDO</span><div className="editorial-word">forma</div><div className="post-card">Ideas que<br/>se sienten.</div></div><div className="project-copy"><h3>Dirección de marca</h3><p>Identidad visual · Contenido · Diseño</p></div></article><article className="project"><div className="project-media media-two"><div className="phone"><span>NUBA SOCIAL</span><b>Haz que<br/>te vean.</b><small>ESTRATEGIA DIGITAL</small></div></div><div className="project-copy"><h3>Contenido para redes</h3><p>Foto · Video · Reels</p></div></article><article className="project"><div className="project-media media-three"><b>menos ruido.<br/><i>más conexión.</i></b><span>CAMPAÑAS CON PROPÓSITO</span></div><div className="project-copy"><h3>Campañas creativas</h3><p>Concepto · Piezas digitales</p></div></article></div><p className="portfolio-note">Estos espacios están preparados para incorporar tus proyectos y fotografías reales.</p></div></section>
   <section className="section" id="metodo"><div className="container"><p className="eyebrow">03 / Método NUBA</p><h2 className="section-title">Tú conoces tu negocio.<br/>Nosotras te ayudamos a mostrarlo.</h2><div className="process">{process.map(([n,t,d])=><article className="step" key={n}><span className="service-no">{n}</span><div><h3>{t}</h3><p>{d}</p></div></article>)}</div></div></section>
   <section className="section" id="nuba"><div className="container about-grid"><div className="about-visual"><span className="corner tl">⌜</span><span className="corner br">⌟</span><b>N</b><p>ESTRATEGIA / CREATIVIDAD / CONEXIÓN</p></div><div className="about-copy"><p className="eyebrow">04 / Sobre NUBA</p><h2 className="section-title">Somos NUBA<span>.</span></h2><p>NUBA nace para ayudar a negocios a verse y comunicarse mejor, con un servicio cercano y contenido pensado para cada realidad.</p><p>Antes de crear, conocemos tu negocio. Luego proponemos una forma clara de mostrarlo y convertimos sus ideas en contenido profesional.</p><p className="location"><strong>Camaná, Arequipa.</strong><br/>Creatividad local con una mirada grande.</p><a className="inline-link" href={instagram} target="_blank" rel="noreferrer">Conócenos en Instagram →</a></div></div></section>
   <section className="cta" id="contacto"><div className="container"><p className="eyebrow">05 / Hablemos</p><h2 className="section-title">Tu negocio tiene algo que contar. Hagamos que más personas lo conozcan<span>.</span></h2><p className="lead">Cuéntanos qué tienes en mente y te ayudaremos a encontrar la mejor forma de mostrarlo.</p><div className="hero-actions"><a className="btn btn-primary" href={whatsapp} target="_blank" rel="noreferrer">Escríbenos por WhatsApp →</a><a className="btn btn-dark-outline" href={email}>Enviar un correo</a></div><div className="contact-box"><a href={whatsapp}>+51 941 075 992</a><a href={email}>nubaagenciacreativa@gmail.com</a><a href={instagram}>@nuba.agenciacreativa</a></div></div></section>
  </main>
  <footer className="footer"><div className="container footer-grid"><a className="brand" href="#inicio">NUBA<span>.</span></a><span>Agencia Creativa · Camaná, Arequipa</span><span>© {new Date().getFullYear()} NUBA</span></div></footer><a className="floating" href={whatsapp} target="_blank" rel="noreferrer">Hablemos ↗</a>
 </>;
}
