"use client";
import { useEffect, useState } from "react";

const whatsapp="https://wa.me/51941075992?text=Hola%20NUBA%2C%20quiero%20contarte%20sobre%20mi%20negocio";
const instagram="https://instagram.com/nuba.agenciacreativa";
const email="mailto:nubaagenciacreativa@gmail.com";
const services=[
 ["01","Contenido","Fotografía, video, reels y contenido con IA para mostrar tu producto, servicio y forma de trabajar."],
 ["02","Redes Sociales","Estrategia, gestión de contenido y campañas para construir una presencia constante, clara y profesional."],
 ["03","Diseño","Identidad visual, piezas gráficas, materiales comerciales y páginas web pensadas para comunicar y vender mejor."]
];
const process=[
 ["01","Descubre","Conocemos tu negocio y lo que quieres lograr."],["02","Planifica","Definimos una ruta clara para tu contenido."],["03","Crea","Producimos las piezas con dirección visual."],["04","Conecta","Llevamos tu mensaje a las personas correctas."],["05","Impulsa","Medimos, aprendemos y seguimos creciendo."]
];
const graphics=[9,8,7,6,5,4,3,2,1];
const videos=[["flameadito.mp4","Contenido para El Flameadito"],["inventario-hidratop.mp4","Contenido comercial"],["razones-hidratop.mp4","Contenido informativo"],["playa.mp4","Producción lifestyle"],["san-valentin.mov","Campaña de temporada"],["kekitos-fit.mp4","Video de producto"],["video - hidratop.mp4","Contenido para Hidratop"],["video comercial - fernandez catering.mp4","Contenido comercial para Fernández Catering"],["video tortas - fernandez catering.mp4","Producto para Fernández Catering"],["video - krysfit.mp4","Contenido para Krysfit"]];
const clientLogos=["client-01.png","client-02.png","client-03.png","client-04.png","client-05.png","client-06.png"];
const aiProjects=[
 {file:"ia-video-01.mp4",brand:"Piscos MOCAMA",format:"vertical"},
 {file:"ia-video-02.mp4",brand:"HIDRATOP",format:"vertical"},
 {file:"ia-video-03.mp4",brand:"EL IMPERIO",format:"vertical"},
 {file:"video 4.mp4",brand:"Proyecto",format:"horizontal"},
 {file:"video 5.mp4",brand:"Contenido Político",format:"horizontal"}
];

function Icon({name}:{name:"whatsapp"|"mail"|"instagram"|"phone"}){
 const paths={whatsapp:<><path d="M21 11.5a8.4 8.4 0 0 1-9 8.5 9.1 9.1 0 0 1-3.8-.9L3 21l1.8-5a8.7 8.7 0 1 1 16.2-4.5Z"/><path d="M8.2 8.1c.3-.7.6-.7.9-.7h.4c.2 0 .4.1.5.5l.8 1.9c.1.3.1.5-.1.7l-.6.8c-.2.2-.2.4-.1.6.6 1.2 1.6 2.2 2.8 2.8.3.1.5.1.7-.1l.8-1c.2-.3.5-.3.8-.2l1.9.9c.3.1.5.3.5.5 0 .7-.4 1.5-.9 2-.6.6-1.4.9-2.3.8-1.5-.2-3.7-1.1-5.4-2.7-1.5-1.4-2.4-3.1-2.6-4.4-.2-1 .2-1.8.7-2.4.4-.3.8-.2 1.2 0Z"/></>,mail:<><rect x="3" y="5" width="18" height="14" rx="2"/><path d="m4 7 8 6 8-6"/></>,instagram:<><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><path d="M17.5 6.5h.01"/></>,phone:<path d="M7.2 3.5 10 7.1 8.4 9.3c1.1 2.5 3 4.4 5.5 5.5l2.2-1.6 3.6 2.8c.5.4.6 1 .4 1.6-.5 1.4-1.8 2.4-3.3 2.3C10.1 19.4 4.6 13.9 4.1 7.2 4 5.7 5 4.4 6.4 3.9c.3-.1.6-.2.8-.4Z"/>};
 return <svg className="icon" viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">{paths[name]}</svg>
}

export default function Home(){
 const [open,setOpen]=useState(false); const [showIntro,setShowIntro]=useState(true); const [formStatus,setFormStatus]=useState<"idle"|"sending"|"sent"|"error">("idle"); const close=()=>setOpen(false);
 useEffect(()=>{const reduced=window.matchMedia("(prefers-reduced-motion: reduce)").matches;document.body.style.overflow="hidden";const timer=window.setTimeout(()=>{setShowIntro(false);document.body.style.overflow=""},reduced?250:2700);return()=>{window.clearTimeout(timer);document.body.style.overflow=""}},[]);
 useEffect(()=>{const items=document.querySelectorAll<HTMLElement>("main > section");const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add("is-visible");observer.unobserve(entry.target)}}),{threshold:.08});items.forEach(item=>{item.classList.add("reveal");observer.observe(item)});return()=>observer.disconnect()},[]);
 useEffect(()=>{if(window.matchMedia("(prefers-reduced-motion: reduce)").matches)return;const clips=document.querySelectorAll<HTMLVideoElement>(".video-gallery video");const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{const video=entry.target as HTMLVideoElement;if(entry.isIntersecting)video.play().catch(()=>{});else video.pause()}),{threshold:.45});clips.forEach(video=>observer.observe(video));return()=>observer.disconnect()},[]);
 const sendForm=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();setFormStatus("sending");const form=e.currentTarget;try{const response=await fetch("https://formspree.io/f/mqpkzrke",{method:"POST",body:new FormData(form),headers:{Accept:"application/json"}});if(!response.ok)throw new Error();form.reset();setFormStatus("sent")}catch{setFormStatus("error")}};
 return <>
  <div className={showIntro?"intro-splash":"intro-splash intro-done"} aria-hidden="true"><div className="intro-logo"><span>N</span><span>U</span><span>B</span><span>A</span><i/></div><p>AGENCIA CREATIVA · CAMANÁ</p></div>
  <a className="skip-link" href="#contenido">Saltar al contenido</a>
  <header className="site-header"><div className="container nav"><a className="brand brand-image" href="#inicio" onClick={close}><img src="/media/brand/nuba-header.png" alt="NUBA Agencia Creativa"/></a><nav className="nav-links"><a href="#servicios">Servicios</a><a href="#trabajos">Portafolio</a><a href="#metodo">Método</a><a href="#nuba">Sobre NUBA</a><a className="btn btn-primary" href={whatsapp} target="_blank" rel="noreferrer">Hablemos</a></nav><button className="menu-btn" onClick={()=>setOpen(!open)} aria-expanded={open}>Menú</button></div><nav className={open?"mobile-menu open":"mobile-menu"}><a href="#servicios" onClick={close}>Servicios</a><a href="#trabajos" onClick={close}>Portafolio</a><a href="#metodo" onClick={close}>Método</a><a href="#nuba" onClick={close}>Sobre NUBA</a><a href={whatsapp}>Hablemos →</a></nav></header>
  <main id="contenido">
   <section className="hero" id="inicio"><div className="container hero-grid"><div><p className="eyebrow">NUBA / Agencia Creativa</p><h1>Creamos contenido para hacer crecer tu negocio<span>.</span></h1><div className="hero-mark"/></div><div className="hero-copy"><p className="hero-sub">Redes sociales · Fotografía · Video · Diseño</p><p className="lead">Contenido claro, profesional y pensado para mostrar lo mejor de tu negocio.</p><div className="hero-actions"><a className="btn btn-primary" href={whatsapp} target="_blank" rel="noreferrer">Cuéntanos sobre tu negocio →</a><a className="btn" href="#trabajos">Ver trabajos</a></div></div><div className="visual-strip"><div className="visual visual-main"><div className="camera-frame"><i>REC</i><strong>Tu negocio<br/>merece ser visto.</strong><span>PRODUCCIÓN DE CONTENIDO</span></div></div><div className="visual visual-light"><div className="nuba-card"><small>CREATIVIDAD<br/>CON DIRECCIÓN</small><b>N.</b><span>CAMANÁ / AREQUIPA</span></div></div></div></div></section>
   <section className="section" id="servicios"><div className="container"><p className="eyebrow">01 / Servicios</p><h2 className="section-title">¿Cómo podemos ayudarte?</h2><div className="services-grid">{services.map(([n,t,d])=><article className="service-row" key={n}><span className="service-no">{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></div></section>
   <section className="section work-section" id="trabajos"><div className="container"><p className="eyebrow">02 / Portafolio</p><h2 className="section-title">Ideas que ya tomaron forma.</h2><p className="lead">Una selección de videos, piezas gráficas y exploraciones creativas realizadas por NUBA.</p><div className="portfolio-tabs"><a href="#videos">Videos</a><a href="#piezas">Piezas gráficas</a><a href="#contenido-ia">Contenido con IA</a></div><div className="portfolio-heading" id="videos"><p className="eyebrow">VIDEO / PRODUCCIÓN</p><h3>Contenido en movimiento.</h3></div><div className="video-gallery">{videos.map(([file,label])=><article key={file}><video muted loop playsInline preload="metadata" aria-label={label}><source src={`/media/video/${file}#t=0.001`}/></video></article>)}</div><div className="portfolio-heading graphics-heading" id="piezas"><p className="eyebrow">DISEÑO / PIEZAS GRÁFICAS</p><h3>Diseño que comunica.</h3></div><div className="real-gallery">{graphics.map(n=><a href={`/media/graphics/pieza-0${n}.jpg`} target="_blank" key={n}><img src={`/media/graphics/pieza-0${n}.jpg`} alt={`Pieza gráfica de NUBA ${n}`} loading="lazy"/></a>)}</div><div id="contenido-ia" className="ai-heading"><p className="eyebrow">CREACIÓN CON IA</p><h3>Nuevas herramientas.<br/>La misma intención.</h3><p>Contenido audiovisual donde la inteligencia artificial amplía las posibilidades creativas de cada idea.</p></div><div className="ai-video-gallery">{aiProjects.map(project=><article className={`ai-project ${project.format}`} key={project.file}><video autoPlay muted loop playsInline preload="metadata" aria-label={`Creación con inteligencia artificial para ${project.brand}`}><source src={`/media/ai/${project.file}#t=0.001`} type="video/mp4"/></video><span>IA × NUBA / {project.brand}</span></article>)}</div></div></section>
   <section className="brands section"><div className="container"><p className="eyebrow">MARCAS CON LAS QUE HEMOS TRABAJADO</p></div><div className="logo-marquee"><div className="logo-track">{[...clientLogos,...clientLogos].map((logo,i)=><div className="logo-slide" key={`${logo}-${i}`} aria-hidden={i>=clientLogos.length}><img src={`/media/client-logos/${logo}`} alt={i<clientLogos.length?`Marca con la que NUBA ha trabajado ${i+1}`:""}/></div>)}</div></div></section>
   <section className="section" id="metodo"><div className="container"><p className="eyebrow">03 / Método NUBA</p><h2 className="section-title">Tú conoces tu negocio.<br/>NUBA te ayuda a mostrarlo.</h2><div className="process">{process.map(([n,t,d])=><article className="step" key={n}><span className="service-no">{n}</span><div><h3>{t}</h3><p>{d}</p></div></article>)}</div></div></section>
   <section className="section" id="nuba"><div className="container about-grid"><div className="about-visual"><span className="corner tl">⌜</span><span className="corner br">⌟</span><img src="/media/brand/nuba-mark.png" alt="Símbolo NUBA: N con punto"/><p>ESTRATEGIA / CREATIVIDAD / CONEXIÓN</p></div><div className="about-copy"><p className="eyebrow">04 / Sobre NUBA</p><h2 className="section-title">Somos NUBA<span>.</span></h2><p>NUBA nace para ayudar a negocios a verse y comunicarse mejor, con un servicio cercano y contenido pensado para cada realidad.</p><p>Antes de crear, conocemos tu negocio. Luego proponemos una forma clara de mostrarlo y convertimos sus ideas en contenido profesional.</p><p className="location"><strong>Camaná, Arequipa.</strong><br/>Creatividad local con una mirada grande.</p><a className="inline-link icon-link" href={instagram} target="_blank" rel="noreferrer"><Icon name="instagram"/> Conócenos en Instagram →</a></div></div></section>
   <section className="cta" id="contacto"><div className="container contact-layout"><div className="contact-copy"><p className="eyebrow">05 / Hablemos</p><h2 className="section-title">Tu negocio tiene algo que contar<span>.</span></h2><p className="lead">Cuéntanos qué tienes en mente y te ayudaremos a encontrar la mejor forma de mostrarlo.</p><div className="hero-actions"><a className="btn btn-primary icon-link" href={whatsapp} target="_blank" rel="noreferrer"><Icon name="whatsapp"/> WhatsApp →</a><a className="btn btn-dark-outline icon-link" href={email}><Icon name="mail"/> Correo</a></div><div className="contact-box"><a className="icon-link" href={whatsapp}><Icon name="phone"/><span>+51 941 075 992</span></a><a className="icon-link" href={email}><Icon name="mail"/><span>nubaagenciacreativa@gmail.com</span></a><a className="icon-link" href={instagram}><Icon name="instagram"/><span>@nuba.agenciacreativa</span></a></div></div><form className="contact-form" onSubmit={sendForm}><div className="form-head"><span>CUÉNTANOS SOBRE TU PROYECTO</span><b>01—06</b></div><label>Tu nombre<input name="nombre" type="text" placeholder="¿Cómo te llamas?" required/></label><label>Nombre de tu negocio<input name="negocio" type="text" placeholder="Nombre de la marca o negocio" required/></label><div className="form-pair"><label>Correo<input name="email" type="email" placeholder="hola@tunegocio.com" required/></label><label>WhatsApp<input name="whatsapp" type="tel" placeholder="+51 999 999 999" required/></label></div><label>¿Qué servicio te interesa?<select name="servicio" required defaultValue=""><option value="" disabled>Selecciona una opción</option><option>Gestión de redes sociales</option><option>Creación de contenido</option><option>Campaña publicitaria</option><option>Identidad visual</option><option>Diseño para mi negocio</option><option>Contenido con IA</option><option>No estoy segura/o todavía</option></select></label><label>Cuéntanos un poco más<textarea name="mensaje" rows={4} placeholder="¿Qué te gustaría lograr con tu marca?" required/></label><input type="text" name="_gotcha" className="form-trap" tabIndex={-1} autoComplete="off"/><button className="form-submit" type="submit" disabled={formStatus==="sending"}>{formStatus==="sending"?"Enviando…":"Enviar mi consulta →"}</button>{formStatus==="sent"&&<p className="form-message success">¡Gracias por escribirnos! Revisaremos tu proyecto y te responderemos muy pronto.</p>}{formStatus==="error"&&<p className="form-message error">No pudimos enviar el formulario. Inténtalo nuevamente o escríbenos por WhatsApp.</p>}</form></div></section>
  </main>
  <footer className="footer"><div className="container footer-grid"><a className="brand brand-image footer-logo" href="#inicio"><img src="/media/brand/nuba-footer.png" alt="NUBA Agencia Creativa"/></a><span>Agencia Creativa · Camaná, Arequipa</span><span>© {new Date().getFullYear()} NUBA</span></div></footer><a className="floating" href={whatsapp} target="_blank" rel="noreferrer" aria-label="Solicitar una cotización a NUBA por WhatsApp"><Icon name="whatsapp"/><span className="floating-copy"><b>WhatsApp</b><b>Solicitar cotización</b></span></a>
 </>;
}
